top_like_tags/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from top_like_tags import views
from django.conf.urls.static import static
from django.conf import settings
from top_like_tags import models


app_name = 'top_like_tags'


urlpatterns = [
    path('', views.index, name='index'),
    path('popular_hashtags/', views.fixed, name='fixed_hashtag'),
    path('hashtag_tips/', views.forums, name='forums'),
    path('about/', views.about, name='about'),
    path('policy/', views.policy, name='policy'),
    path('contact/', views.contact, name='contact'),
    re_path('blog/(?P<blog_id>[\w-]+)', views.full_blog, name='full_blog'),
    # path('generator/', views.generator.as_view(), name='generator'),
    path('generator/', views.generator, name='generator'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topliketags/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('top_like_tags.urls')),
    path(
        "ads.txt",
        RedirectView.as_view(url=staticfiles_storage.url("ads.txt")),
    ),
    path(
        "sitemap.xml",
         RedirectView.as_view(url=staticfiles_storage.url("sitemap.xml")),
    ),
    path('oneandonly/', admin.site.urls),
]

top_like_tags/models.py
from django.db import models


class home(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class about(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class hashtag_tips(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class most_popular_hashtags(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class contact_page(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class policy_page(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=3000)
    keywords = models.CharField(max_length=3000)

class blog_posts(models.Model):
    blogimg = models.FileField(null=False, blank=False)
    blogurl = models.CharField(max_length=100)
    seotitle = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000)
    keyword = models.CharField(max_length=1000)
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=2000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class fixed_hashtag(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    hashtags = models.CharField(max_length=2000)

    def __str__(self):
        return self.title


class analytics(models.Model):
    home_page = models.IntegerField()
    popular_hashtag = models.IntegerField()
    forums = models.IntegerField()
    full_blog = models.IntegerField()
    contact = models.IntegerField()

top_like_tags/views.py
import browser_cookie3
import requests
import json
import os
import random
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .models import blog_posts, fixed_hashtag, analytics
from top_like_tags import models
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.base import View

import os
from django.conf import settings

from selenium import webdriver
from time import sleep
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support import ui
from selenium.webdriver.common.by import By
from django.http import HttpResponse

def about(request):
    m = models.about.objects.all().first()
    return render(request, 'top_like_tags/about.html', {'seo': m})

def policy(request):
    m = models.policy_page.objects.all().first()
    return render(request, 'top_like_tags/policy.html', {'seo': m})

def index(request):
    m = models.home.objects.all().first()
    a = analytics.objects.all().first()
    a.home_page = a.home_page+1
    a.save()
    model = blog_posts.objects.all().order_by('-date')
    if len(model) < 4:
        pass
    else:
        model = model[:4]
    data = {
        'blog': model,
        'seo': m
    }
    return render(request, 'top_like_tags/index.html', data)


def fixed(request):
    m = models.fixed_hashtag.objects.all().first()
    a = analytics.objects.all().first()
    a.popular_hashtag = a.popular_hashtag+1
    a.save()
    model = fixed_hashtag.objects.all()
    data = {
        'fixed_hash': model,
        'seo': m
    }
    return render(request, 'top_like_tags/fixed_hashtag.html', data)


def full_blog(request, blog_id):
    a = analytics.objects.all().first()
    a.full_blog = a.full_blog+1
    a.save()
    model = blog_posts.objects.get(blogurl=blog_id)
    return render(request, 'top_like_tags/full_blog.html', {'blog': model})


def forums(request):
    m = models.hashtag_tips.objects.all().first()

    a = analytics.objects.all().first()
    a.forums = a.forums+1
    a.save()
    model = blog_posts.objects.all().order_by('-date')
    data = {
        'blog': model,
        'seo': m
    }
    return render(request, 'top_like_tags/forums.html', data)

def contact(request):
    if request.method == 'POST':
        name = request.POST['id_name']
        email = request.POST['id_email']
        message = request.POST['id_msg']

        msg = MIMEMultipart('alternative')
        msg['Subject'] = 'New Email from TopLikeTags.com'
        html = """
            <html>
              <head></head>
              <body>
                <h1>Hi Admin</h1>
                <p>You Just Got An Email From %s. Please Mail Him Back On %s.</p>
                <p>Message : %s</p>
              </body>
            </html>
            """ % (name, email, message)
        part2 = MIMEText(html, 'html')
        msg.attach(part2)
        smtp_server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        smtp_server.login('topliketagscontact@gmail.com', 'Helloworld20,')
        smtp_server.sendmail("topliketagscontact@gmail.com", 'topliketags@gmail.com', msg.as_string())
        smtp_server.close()
        # return redirect('top_like_tags:index')
        remark = 'Your message has been sent.'
        return render(request, 'top_like_tags/contact.html', {'remark': remark})
    else:
        m = models.contact_page.objects.all().first()
        
        a = analytics.objects.all().first()
        a.contact = a.contact+1
        a.save()
        data = {
            'seo': m
        }
        return render(request, 'top_like_tags/contact.html')


def generator(request):
    path_of_file = os.path.join(settings.BASE_DIR, 'static')
    full_path = path_of_file+'/topliketags-profile/Default/Cookies'
    cookies = browser_cookie3.chrome(cookie_file=full_path)
    hashtag = request.POST['keyword']
    random_text = request.POST['random']
    search_url = 'https://www.instagram.com/web/search/topsearch/'
    explore_headers = {'Host': 'www.instagram.com',
                        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0',
                        'Accept': '*/*',
                        'Accept-Language': 'en-US;q=0.7,en;q=0.3',
                        'Accept-Encoding': 'gzip, deflate, br',
                        'X-Requested-With': 'XMLHttpRequest',
                        'Referer': 'https://www.instagram.com/',
                        'Connection': 'keep-alive'}
    if hashtag[0] != '#':
        hashtag = '#' + hashtag
        params = {'context': 'blended',
            'query': hashtag,
            'rank_token': random.uniform(0, 1)}

    s = requests.Session()
    request = s.get(search_url, params=params, verify=False, headers=explore_headers, cookies=cookies, timeout=3)
    response = None
    if request.status_code == 200:
        response = request
    else:
        raise requests.HTTPError(str(request.status_code))
    tag_list = response.json()['hashtags']
    tags = []

    for tag in tag_list:
        if tag == '':
            pass
        else:
            tags.append('#'+tag['hashtag']['name']+' ')
    if int(random_text) == 1:
        return HttpResponse(random.sample(tags, 30))
    return HttpResponse(tags[30:])

top_like_tags/templates/top_like_tags/forums.html
{% load static %}
<head>
    {% if seo %}
    <title>{{ seo.title }}</title>
    <meta charset="UTF-8">
    <meta name="description" content="{{ seo.description }}">
    <meta name="keywords" content="{{ seo.keywords }}">
    {% endif %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'flaticon/font/flaticon.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'animate.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open Sans|Playfair Display|Work Sans|Cormorant Garamond|Lora|Lobster|Josefin Sans|Roboto|Dancing Script|Abril Fatface|&display=swap" rel="stylesheet">
<script data-ad-client="ca-pub-3557075530543855" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-52514727-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-52514727-1');
</script>
    <style>
        body{
            font-family: 'Josefin Sans';
        }
        @media(max-width: 1100px){

        }
        @media(max-width: 650px){
            .ftxt{
                display: none !important;
            }
            .ftxt_show{
                display: block !important;
            }
            .wp{
                 height: 200px !important;
            }
            .navbar-img{
                text-align: center !important;
                width: 70% !important;
            }
            .navbar-toggler{
                position: absolute;
            }
            .navbar-collapse{
                text-align: right;
            }
            .navbar{
                height: auto !important;
            }
            .main_tab{
                margin: 10px 0px 0px 0px !important;
            }
            .main_part, .overlay{
                height: 500px;
            }
        }
        a{
            text-decoration: none;
        }
        html{
            scroll-behavior: smooth;
        }
        .nav_id{
            font-weight: 700;
            font-size: 1rem;
            {#color: #4b4b4b;#}
            color: white;
        }
        .nav_id:hover{
            text-decoration: none !important;
            transition: ease 0.5s;
            color: #00e1ff !important;
        }
        @media(max-width: 770px){
            .ftxt{
                display: none !important;
            }
            .ftxt_show{
                display: block !important;
            }
            .wp{
                 height: 200px !important;
            }
            .navbar-img{
                text-align: center !important;
                width: 70% !important;
            }
            .navbar-toggler{
                position: absolute;
            }
            .navbar-collapse{
                text-align: right;
            }
            .navbar{
                height: auto !important;
            }
            .main_tab{
                margin: 10px 0px 0px 0px !important;
            }
            .main_part{
                height: 450px !important;
            }
            .overlay{
                height: 450px !important;
            }
        }
        div.main_part{
            z-index: 2;
            width: 100%;
            height: 600px;
            position: absolute;
            box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);
            background: url("{% static 'bg.jpg' %}");
            background-position: center;
            background-size: cover;
            opacity: 0.8;
            background-repeat: no-repeat;
        }
        .navbar-img:hover{
            cursor: pointer;
        }
         div.overlay{
            z-index: 3;
            width: 100%;
            height: 600px;
            position: absolute;
            box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);
            border-radius: 5px;
            {#background-color: rgba(255, 255, 255, 0.15);#}
            background-color: rgba(0, 0, 0, 0.57);
            backdrop-filter: blur(3px);
            color: #fff;
        }
        .nv{
            background: rgba(0, 0, 0, 0.23);
            {#background: rgba(255, 255, 255, 0.62);#}
            z-index: 4;
            color: white;
        }
        .nav-link{
            color: white !important;
                font-weight: 900 !important;
        }
        .nav-link:hover{
            transition: ease 0.5s;
            color: #000000 !important;
        }
        .navbar-toggler {
            border: none !important;
        }
        .btn:link,
        .btn:visited {
            text-transform: uppercase;
            text-decoration: none;
            padding: 15px 40px;
            display: inline-block;
            border-radius: 100px;
            transition: all .2s;
            position: absolute;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        }

        .btn-white {
            background-color: #fff;
            color: #777;
        }

        .btn::after {
            content: "";
            display: inline-block;
            height: 100%;
            width: 100%;
            border-radius: 100px;
            position: absolute;
            top: 0;
            left: 0;
            z-index: -1;
            transition: all .4s;
        }

        .btn-white::after {
            background-color: #fff;
        }

        .btn:hover::after {
            transform: scaleX(1.4) scaleY(1.6);
            opacity: 0;
        }

        .btn-animated {
            animation: moveInBottom 5s ease-out;
            animation-fill-mode: backwards;
        }

        @keyframes moveInBottom {
            0% {
                opacity: 0;
                transform: translateY(30px);
            }

            100% {
                opacity: 1;
                transform: translateY(0px);
            }
        }
    </style>
</head>
<body>
<style>
.main_part, .overlay{
    display: none;
}

</style>
<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light" style="
border: 0.5px solid rgba(128,128,128,0.25); border-left: none; border-right: none; z-index: 4; background: #17d9db !important;">
    <div class="container mx-auto text-center">
        <button class="navbar-toggler"
                type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button><br>
        <div onclick="window.location.replace('{% url 'top_like_tags:index' %}');"
             class="mx-auto navbar-img text-center" style="width: 300px; padding: 20px;">
            <img alt="topliketags logo" class="mx-auto text-center" style="display: block; max-width: 100%; height: auto;" src="{% static 'horlogo.png' %}"></div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:index' %}">HOME <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:forums' %}">HASHTAG TIPS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:fixed_hashtag' %}">MOST POPULAR HASHTAGS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:contact' %}">CONTACT</a>
                </li>
            </ul><br>
        </div>
    </div>
</nav>
<Br><Br><br>
    <div class="container mx-auto text-center">
        <div style="z-index: 4;">
            <h1 style="color: white;">Forums</h1>
        </div>
    </div>
    <div class="col-md-12 mx-auto text-center">
        <div class="row mx-auto text-center">
            {% if blog %}
                {% for b in blog %}
                    <div class="card mx-auto text-center" style="width: 20rem;  margin: 5px;">
                    {% if seo %}
                        <img alt="{{seo.title}}" class="card-img-top" src="{{ b.blogimg.url }}" style="width: auto; height: 230px;">
                    {% endif %}
                      <div class="card-body text-center">
                        <h5 class="card-title">{{ b.title|truncatechars:60 }}</h5>
                        <p class="card-text">{{ b.text|truncatechars:70 }}</p>
                        <a href="{% url 'top_like_tags:full_blog' blog_id=b.blogurl %}"><button class="btn btn-primary">Read More</button></a>
                      </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
<br><br><br>
<div class="col-md-12">
                <div class="container" style="padding: 10px;">
                    <hr>
                    <div class="row">
                        <div class="mr-auto text-left">
                            <p style="font-size: 0.8rem;">Copyright © 2020 TopLikeTags
                                <a class="ftxt" href="{% url 'top_like_tags:about' %}">| About |</a>
                                <a class="ftxt" href="{% url 'top_like_tags:policy' %}">Privacy |</a>
                                <a class="ftxt" href="{% url 'top_like_tags:contact' %}">Contact</a>
                        </div><br>
                        <div class="ftxt_show mr-auto text-center" style="font-size: 0.8rem; display: none">
                            <a href="{% url 'top_like_tags:about' %}">About</a>
                            <a href="{% url 'top_like_tags:policy' %}">Privacy</a>
                            <a href="{% url 'top_like_tags:contact' %}">Contact</a>
                        </div><Br><Br>
                        <div class="mx-auto text-center">
                            <p style="font-size: 0.8rem;">Need Help? Email hello@topliketags.com</p>
                        </div>
                        <div class="ml-auto text-right">
                            <a href="https://www.instagram.com/topliketags">
                                <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-instagram"></i>
                            </a>
                            <a href="https://www.facebook.com/topliketags">
                                <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-facebook"></i>
                            </a>
        {#                    <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-twitter"></i>#}
        {#                    <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-google-plus"></i>#}
                        </div>
                    </div>
                </div>
            </div>
        </body><script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
        <script>
            AOS.init();
        </script>
    </html>

top_like_tags/templates/top_like_tags/full_blog.html
{% load static %}
<html lang="en">
<head>
    {% if blog.seotitle %}
        <title>{{ blog.seotitle }}</title>
    {% endif %}
    <meta charset="UTF-8">
    {% if blog.description %}
        <meta name="description" content="{{ blog.description }}">
    {% endif %}
    {% if blog.keyword %}
        <meta name="keywords" content="{{ blog.keyword }}">
    {% endif %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'flaticon/font/flaticon.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'animate.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script data-ad-client="ca-pub-3557075530543855" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open Sans|Playfair Display|Work Sans|Cormorant Garamond|Lora|Lobster|Josefin Sans|Roboto|Dancing Script|Abril Fatface|&display=swap" rel="stylesheet">
    <style>
        body{
            font-family: 'Josefin Sans';
        }
        @media(max-width: 1100px){

        }
        @media(max-width: 770px){
            .navbar-img{
                text-align: center !important;
            }
            .navbar-toggler{
                position: absolute;
            }
            .navbar-collapse{
                text-align: right;
            }
            .navbar{
                height: auto !important;
            }
        }
        a{
            text-decoration: none;
        }
        html{
            scroll-behavior: smooth;
        }
        .nav_id{
            font-weight: 700;
            font-size: 1rem;
            {#color: #4b4b4b;#}
            color: white;
        }
        .nav_id:hover{
            text-decoration: none !important;
            transition: ease 0.5s;
            color: #00e1ff !important;
        }
        div.main_part{
            z-index: 2;
            width: 100%;
            height: 750px;
            position: absolute;
            box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);
            background: url("{% static 'bg.jpg' %}");
            background-position: center;
            background-size: cover;
            opacity: 0.8;
            background-repeat: no-repeat;
        }
         div.overlay{
            z-index: 3;
            width: 100%;
            height: 750px;
            position: absolute;
            box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);
            border-radius: 5px;
            {#background-color: rgba(255, 255, 255, 0.15);#}
            background-color: rgba(0, 0, 0, 0.57);
            backdrop-filter: blur(3px);
            color: #fff;
        }
        .nv{
            background: rgba(0, 0, 0, 0.23);
            {#background: rgba(255, 255, 255, 0.62);#}
            z-index: 4;
            color: white;
        }
        .nav-link{
            color: white !important;
                font-weight: 900 !important;
        }
        .nav-link:hover{
            transition: ease 0.5s;
            color: #000000 !important;
        }
        .navbar-toggler {
            border: none !important;
        }
        @media(max-width: 770px){
            .blg_img{
                padding: 10px;
                width: 320px !important;
            }
        }
    </style>
</head>
<body>
<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light" style="
border: 0.5px solid rgba(128,128,128,0.25); border-left: none; border-right: none; z-index: 4; background: #17d9db !important;">
    <div class="container mx-auto text-center">
        <button class="navbar-toggler"
                type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button><br>
        <div onclick="window.location.replace('{% url 'top_like_tags:index' %}');"
             class="mx-auto navbar-img text-center" style="width: 300px; padding: 20px;">
            <img alt="topliketags logo" class="mx-auto text-center" style="display: block; max-width: 100%; height: auto;" src="{% static 'horlogo.png' %}"></div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:index' %}">HOME <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:about' %}">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:forums' %}">HASHTAG TIPS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:fixed_hashtag' %}">MOST POPULAR HASHTAGS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'top_like_tags:contact' %}">CONTACT</a>
                </li>
            </ul><br>
        </div>
    </div>
</nav>
<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
<script>
    AOS.init();
</script>
<Br><Br><br>
    <div class="container mx-auto text-center">
            {% if blog %}
                  <div class="blg_img mx-auto text-center" style="width: 100%; height: auto;"><img src="{{ blog.blogimg.url }}" style="max-width: 100%; height: auto; display: block;" alt="Card image cap"></div>
                    <br><Br>
                  <div class="text-left mx-auto" style="padding: 20px;">
                    <h1 class="title mx-auto">{{ blog.title }}</h1><hr>
                    <p class="text mx-auto">{{ blog.text|safe|linebreaks }}</p>
                  </div>
            {% else %}
                <h5 class="title">No Blog's Exists With That ID</h5><hr>
            {% endif %}
                </div>
            <br><br><br><br>

            <div class="col-md-12">
                <div class="container" style="padding: 10px;">
                    <hr>
                    <div class="row">
                        <div class="mr-auto text-left">
                            <p style="font-size: 0.8rem;">Copyright © 2020 TopLikeTags
                                <a class="ftxt" href="{% url 'top_like_tags:about' %}">| About |</a>
                                <a class="ftxt" href="{% url 'top_like_tags:policy' %}">Privacy |</a>
                                <a class="ftxt" href="{% url 'top_like_tags:contact' %}">Contact</a>
                        </div><br>
                        <div class="ftxt_show mr-auto text-center" style="font-size: 0.8rem; display: none">
                            <a href="{% url 'top_like_tags:about' %}">About</a>
                            <a href="{% url 'top_like_tags:policy' %}">Privacy</a>
                            <a href="{% url 'top_like_tags:contact' %}">Contact</a>
                        </div><Br><Br>
                        <div class="mx-auto text-center">
                            <p style="font-size: 0.8rem;">Need Help? Email hello@topliketags.com</p>
                        </div>
                        <div class="ml-auto text-right">
                            <a href="https://www.instagram.com/topliketags">
                                <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-instagram"></i>
                            </a>
                            <a href="https://www.facebook.com/topliketags">
                                <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-facebook"></i>
                            </a>
        {#                    <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-twitter"></i>#}
        {#                    <i style="margin: 0px 4px 0px 4px; font-size: 1.5rem;" class="fab fa-google-plus"></i>#}
                        </div>
                    </div>
                </div>
            </div><script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
            <script>
                AOS.init();
            </script>
</body>
</html>